server:
  port: 9000
  forward-headers-strategy: native

cloud:
#  db-host: localhost
  eureka-host: localhost
  bank-app-url: http://localhost:8080

spring:
#  security:
#    oauth2:
#      authorizationserver:
#        issuer: http://localhost:8080/auth
  application:
    name: auth-service
  datasource:
    url: jdbc:h2:mem:auth-db
    driverClassName: org.h2.Driver
    username: sa
    password: password
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect

eureka:
  client:
    enabled: false
    service-url:
      defaultZone: http://${cloud.eureka-host}:8761/eureka
