server:
  port: 8182

cloud:
  auth-host: localhost
  db-host: localhost
  eureka-host: localhost
  currency-host: localhost
  currency-port: 8181

spring:
  application:
    name: exchange-processing-service
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://${cloud.db-host}:5432/processing
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    url: jdbc:postgresql://${cloud.db-host}:5432/processing
    user: postgres
    password: password

eureka:
  client:
    enabled: false
    service-url:
      defaultZone: http://${cloud.eureka-host}:8761/eureka

currency-service:
  host: ${cloud.currency-host}
  port: ${cloud.currency-port}

keySetURI: http://${cloud.auth-host}:9000/oauth2/jwks