server:
  port: 8182

cloud:
  auth-host: localhost
  db-host: localhost
  eureka-host: localhost
  currency-host: localhost
  currency-port: 8181

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${cloud.auth-host}:9000
      client:
        provider:
          my_auth_server:
            token-uri: http://${cloud.auth-host}:9000/oauth2/token
        registration:
          interServiceClient:
            client-id: interServiceClient
            client-name: Inter Service Client
            client-secret: interServiceClientSecret
            authorization-grant-type: client_credentials
            provider: my_auth_server
            client-authentication-method: client_secret_basic
            scope: internal
  application:
    name: exchange-processing-service
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://${cloud.db-host}:5432/processing
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    url: jdbc:postgresql://${cloud.db-host}:5432/processing
    user: postgres
    password: password

eureka:
  client:
    enabled: false
    service-url:
      defaultZone: http://${cloud.eureka-host}:8761/eureka

currency-service:
  host: ${cloud.currency-host}
  port: ${cloud.currency-port}

keySetURI: http://${cloud.auth-host}:9000/oauth2/jwks