version: '3.8'

services:
  eureka-service:
    build:
      context: ./eureka-service
    ports:
      - "8761:8761"

  gateway-service:
    build:
      context: ./gateway-service
    ports:
      - "8080:8080"
    environment:
      EUREKA_HOST: eureka-service
      PROCESSING_URL: http://processing-service:8182
      CURRENCY_URL: lb://currency-service
#      CURRENCY_URL: http://currency-service:8181
    links:
      - currency-service-1
      - currency-service-2
    depends_on:
      - eureka-service

  currency-service-1:
    build:
      context: ./currency-service
    hostname: currency-service-1
    container_name: currency-service-1
    ports:
      - "8281:8181"
    environment:
      EUREKA_HOST: eureka-service
    depends_on:
      - eureka-service

  currency-service-2:
    build:
      context: ./currency-service
    hostname: currency-service-2
    container_name: currency-service-2
    ports:
      - "8381:8181"
    environment:
      EUREKA_HOST: eureka-service
    depends_on:
      - eureka-service

  processing_db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: processing
      PGDATA: /var/lib/postgresql/data
    volumes:
        - ./db/processing/data:/var/lib/postgresql/data
    restart: always

  processing-service:
    build:
      context: ./processing-service
    environment:
      DB_HOST: processing_db
      EUREKA_HOST: eureka-service
      CURRENCY_HOST: currency-service
    ports:
      - "8182:8182"
    depends_on:
      - processing_db
      - eureka-service
