server:
  port: 8181

logging:
  level:
    root: info

spring:
  application:
    name: currency-service

springdoc:
  swagger-ui:
    doc-expansion: none

currency:
  client:
    url: "https://cbr.ru/scripts/XML_daily.asp?"

eureka:
  client:
    enabled: false
    service-url:
      defaultZone: http://localhost:8761/eureka
