server:
  port: 8181

logging:
  level:
    root: info

spring:
  application:
    name: currency

springdoc:
  swagger-ui:
    doc-expansion: none

currency:
  client:
    url: "https://cbr.ru/scripts/XML_daily.asp?"