server:
  port: 8182

spring:
  application:
    name: exchange-processing-service
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/processing
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    url: jdbc:postgresql://localhost:5432/processing
    user: postgres
    password: password

eureka:
  client:
    enabled: false
    service-url:
      defaultZone: http://localhost:8761/eureka

currency-service:
  host: localhost
  port: 8181